server.port=8081

# JWT
security.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_KEY_32CHARS_MIN
security.jwt.expiration=3h

# Configuration OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# API utilisateur (placeholder)
user.api.base-url=
